apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ess-web
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/lanmarqueses/deployment-manifest.git
    targetRevision: master
    path: ess-web-build
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
