apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ess-web                     # any friendly name
  namespace: argocd                      # must always be in argocd ns
spec:
  project: default                       # use "default" unless you made others
  source:
    repoURL: https://github.com/<your-user>/<your-repo>.git
    targetRevision: master                 # branch, tag, or commit SHA
    path: k8s                            # folder in repo with manifests or chart
    # --- Optional if using Helm instead of plain YAML ---
    # helm:
    #   valueFiles:
    #     - values.yaml
  destination:
    server: https://kubernetes.default.svc   # the in-cluster Docker Desktop API
    namespace: app                           # target namespace for your app
  syncPolicy:
    automated:                               # make Argo auto-apply changes
      prune: true                            # delete removed objects
      selfHeal: true                         # resync drifted objects
    syncOptions:
      - CreateNamespace=true                 # auto-create target namespace
