apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: test-project2
  name: test-project2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-world-demo
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: test-project2
    spec:
      containers:
      - image: nanajanashia/argocd-app:1.2
        imagePullPolicy: Always
        name: test-project2
        ports:
          - containerPort: 8080
            name: http
            protocol: TCP
        resources: {}
