apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
  name: test-project2-ingress
spec:
  rules:
    - host: test-project2.sampledomain.com
        http:
          paths:
            - path: /
                pathType: Prefix
                backend:
                  service:
                    name: test-project2-svc
                    port:
                      number: 8080
