apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: test-project2

namespace: default
nameSuffix: -default

resources:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
