apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-project
spec:
  selector:
    matchLabels:
      app: test-project
  replicas: 2
  template:
    metadata:
      labels:
        app: test-project
    spec:
      containers:
      - name: test-project
        image: nanajanashia/argocd-app:1.2
        ports:
        - containerPort: 8080
