apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-project
spec:
  selector:
    matchLabels:
      app: test-project
  replicas: 2
  template:
    metadata:
      labels:
        app: test-project
    spec:
      containers:
      - name: test-project
        image: acrgisdsandboxea.azurecr.io/hello-world-demo/sandbox:latest
        ports:
        - containerPort: 8080
