apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: test-project-demo

namespace: nginx
nameSuffix: -nginx

resources:
- configmap.yaml
- deployment.yaml
- ingress.yaml
- nginx-service.yaml
