apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: hello-world-demo

namespace: sandbox
nameSuffix: -sandbox

resources:
- configmap.yaml
- deployment.yaml
- service.yaml
- ingress.yaml
