apiVersion: v1
kind: Service
metadata:
  name: test-project-svc
spec:
  ingressClass: nginx
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: nginx
  type: ClusterIP
